<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osmformat.proto

namespace OSMPBF;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OSMPBF.HeaderBBox</code>
 */
class HeaderBBox extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>sint64 left = 1;</code>
     */
    protected $left = 0;
    /**
     * Generated from protobuf field <code>sint64 right = 2;</code>
     */
    protected $right = 0;
    /**
     * Generated from protobuf field <code>sint64 top = 3;</code>
     */
    protected $top = 0;
    /**
     * Generated from protobuf field <code>sint64 bottom = 4;</code>
     */
    protected $bottom = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $left
     *     @type int|string $right
     *     @type int|string $top
     *     @type int|string $bottom
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osmformat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>sint64 left = 1;</code>
     * @return int|string
     */
    public function getLeft()
    {
        return $this->left;
    }

    /**
     * Generated from protobuf field <code>sint64 left = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLeft($var)
    {
        GPBUtil::checkInt64($var);
        $this->left = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint64 right = 2;</code>
     * @return int|string
     */
    public function getRight()
    {
        return $this->right;
    }

    /**
     * Generated from protobuf field <code>sint64 right = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRight($var)
    {
        GPBUtil::checkInt64($var);
        $this->right = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint64 top = 3;</code>
     * @return int|string
     */
    public function getTop()
    {
        return $this->top;
    }

    /**
     * Generated from protobuf field <code>sint64 top = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTop($var)
    {
        GPBUtil::checkInt64($var);
        $this->top = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint64 bottom = 4;</code>
     * @return int|string
     */
    public function getBottom()
    {
        return $this->bottom;
    }

    /**
     * Generated from protobuf field <code>sint64 bottom = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setBottom($var)
    {
        GPBUtil::checkInt64($var);
        $this->bottom = $var;

        return $this;
    }

}

