<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osmformat.proto

namespace OSMPBF;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>OSMPBF.Relation</code>
 */
class Relation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     */
    protected $id = 0;
    /**
     * Parallel arrays.
     *
     * Generated from protobuf field <code>repeated uint32 keys = 2 [packed = true];</code>
     */
    private $keys;
    /**
     * Generated from protobuf field <code>repeated uint32 vals = 3 [packed = true];</code>
     */
    private $vals;
    /**
     * Generated from protobuf field <code>optional .OSMPBF.Info info = 4;</code>
     */
    protected $info = null;
    /**
     * Parallel arrays
     *
     * Generated from protobuf field <code>repeated int32 roles_sid = 8 [packed = true];</code>
     */
    private $roles_sid;
    /**
     * DELTA encoded
     *
     * Generated from protobuf field <code>repeated sint64 memids = 9 [packed = true];</code>
     */
    private $memids;
    /**
     * Generated from protobuf field <code>repeated .OSMPBF.Relation.MemberType types = 10 [packed = true];</code>
     */
    private $types;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $id
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $keys
     *           Parallel arrays.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $vals
     *     @type \OSMPBF\Info $info
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $roles_sid
     *           Parallel arrays
     *     @type array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $memids
     *           DELTA encoded
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $types
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Osmformat::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @return int|string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int64 id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Parallel arrays.
     *
     * Generated from protobuf field <code>repeated uint32 keys = 2 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * Parallel arrays.
     *
     * Generated from protobuf field <code>repeated uint32 keys = 2 [packed = true];</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 vals = 3 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getVals()
    {
        return $this->vals;
    }

    /**
     * Generated from protobuf field <code>repeated uint32 vals = 3 [packed = true];</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setVals($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->vals = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .OSMPBF.Info info = 4;</code>
     * @return \OSMPBF\Info|null
     */
    public function getInfo()
    {
        return $this->info;
    }

    public function hasInfo()
    {
        return isset($this->info);
    }

    public function clearInfo()
    {
        unset($this->info);
    }

    /**
     * Generated from protobuf field <code>optional .OSMPBF.Info info = 4;</code>
     * @param \OSMPBF\Info $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkMessage($var, \OSMPBF\Info::class);
        $this->info = $var;

        return $this;
    }

    /**
     * Parallel arrays
     *
     * Generated from protobuf field <code>repeated int32 roles_sid = 8 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRolesSid()
    {
        return $this->roles_sid;
    }

    /**
     * Parallel arrays
     *
     * Generated from protobuf field <code>repeated int32 roles_sid = 8 [packed = true];</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRolesSid($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->roles_sid = $arr;

        return $this;
    }

    /**
     * DELTA encoded
     *
     * Generated from protobuf field <code>repeated sint64 memids = 9 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMemids()
    {
        return $this->memids;
    }

    /**
     * DELTA encoded
     *
     * Generated from protobuf field <code>repeated sint64 memids = 9 [packed = true];</code>
     * @param array<int>|array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMemids($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::SINT64);
        $this->memids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .OSMPBF.Relation.MemberType types = 10 [packed = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTypes()
    {
        return $this->types;
    }

    /**
     * Generated from protobuf field <code>repeated .OSMPBF.Relation.MemberType types = 10 [packed = true];</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \OSMPBF\Relation\MemberType::class);
        $this->types = $arr;

        return $this;
    }

}

